---
# file: roles/idrac-alerts/tasks/main.yml

- debug: var=syslog_servers

- local_action: 
    module: idrac
    username: "{{ lom_user }}"
    password: "{{ lom_pass }}"
    hostname: "{{ lom_hostname }}"
    command: 'SyslogSettings'
    servers: "{{ idrac_syslog_servers }}"
    enable: "{{ idrac_syslog_enable }}"
    port: "{{ idrac_syslog_port }}"
    debug: True
  when: syslog_servers is defined
  tags:
    - idrac_syslog

